site_name: AutoMate - AI Computer Control
site_url: ""
site_description: "Comprehensive documentation for the AutoMate project - LLM-powered tool use for computer control"
site_author: "MLOps Team"

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Getting Started:
      - Introduction: introduction.md
      - Features & Tools: features.md
      - System Architecture: architecture.md
      - Quick Start: setup.md
  - Setup & Usage:
      - Installation: setup/installation.md
      - Configuration: setup/configuration.md
  - About: about.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - footnotes
  - def_list

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/LLM_Tool_Use
    - icon: fontawesome/brands/python
      link: https://python.org
  generator: false
